---
- name: Converge
  hosts: all
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: True
      changed_when: False

- name: Converge
  hosts: all
  gather_facts: True
  become: True
  vars:
    mongo_bind_ip: 0.0.0.0
  roles:
    - role: db
