---
# tasks file for app
- name: add unit file for Puma
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: add config for DB connection
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser
- name: enable puma
  systemd: name=puma enabled=yes

- name: show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

