# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

